name: tests

on:
  push:
    branches: [ master, amrvac3.0 ]
  pull_request:
    branches: [ master, amrvac3.0 ]


jobs:
  GNU:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        FC_compiler: [gfortran-9]
        CC_compiler: [gcc-9]
        suite: [rho, hd, rhd, mhd, rd, ard, mg, twofl]

    env:
      CC: ${{ matrix.CC_compiler }}
      FC: ${{ matrix.FC_compiler }}
      AMRVAC_DIR: ${GITHUB_WORKSPACE}

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.suite }}

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install openmpi-bin libopenmpi-dev
      - name: check compiler versions
        run: |
          ${FC} --version
          ${CC} --version
          mpirun --version
      - name: check code dependencies
        run: |
          cd src
          bash update_dependencies.sh --verbose || exit 1
      - name: compile
        run: |
          cd lib
          make clean
          make -j 2 || exit 1
      - name: run tests
        run: |
          cd tests
          bash test_runner.sh ${{ matrix.suite }}
